matrix:
  VARIATION:
    - normal
    - alpine
  VERSION:
    - 1.4.2
    - 1.5.3
    - 1.6rc1

publish:
  armhfbuild_1.4.2_alpine:
    image: armhfplugins/drone-docker
    file: "$$VERSION/alpine/Dockerfile"
    context: "$$VERSION/alpine"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/golang
    tag:
      - "$$VERSION-alpine"
      - "1.4-alpine"
    force_tag: true
    when:
      matrix:
        VERSION: 1.4.2
        VARIATION: alpine
      
  armhfbuild_1.4.2:
    image: armhfplugins/drone-docker
    file: "$$VERSION/Dockerfile"
    context: "$$VERSION"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/golang
    tag:
      - "$$VERSION"
      - "1.4"
    force_tag: true
    when:
      matrix:    
        VARIATION: normal
        VERSION: 1.4.2

  armhfbuild_1.5.3:
    image: armhfplugins/drone-docker
    file: "$$VERSION/Dockerfile"
    context: "$$VERSION"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/golang
    tag:
      - "$$VERSION"
      - "1.5"
      - "latest"
    force_tag: true
    when:
      matrix:
        VERSION: 1.5.3
        VARIATION: normal

  armhfbuild_1.5.3_alpine:
    image: armhfplugins/drone-docker
    file: "$$VERSION/alpine/Dockerfile"
    context: "$$VERSION/alpine"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/golang
    tag:
      - "$$VERSION-alpine"
      - "1.5-alpine"
    force_tag: true
    when:
      matrix:
        VERSION: 1.5.3
        VARIATION: alpine

  armhfbuild_1.6rc1:
    image: armhfplugins/drone-docker
    file: "$$VERSION/Dockerfile"
    context: "$$VERSION"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/golang
    tag:
      - "$$VERSION"
      - "1.6"
    force_tag: true
    when:
      matrix:
        VERSION: 1.6rc1
        VARIATION: normal

  armhfbuild_1.6rc1_alpine:
    image: armhfplugins/drone-docker
    file: "$$VERSION/alpine/Dockerfile"
    context: "$$VERSION/alpine"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/golang
    tag:
      - "$$VERSION-alpine"
      - "1.6-alpine"
    force_tag: true
    when:
      matrix:
        VERSION: 1.6rc1
        VARIATION: alpine
