matrix:
  VERSION:
    - 1.5.3
    - 1.6rc1

publish:
  docker:
    file: $$VERSION/Dockerfile
    context: "$$VERSION"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/golang
    tag: "$$VERSION"
    storage_driver: overlay
