FROM armhfbuild/buildpack-deps:jessie-scm

# gcc for cgo
RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    gcc \
    libc6-dev \
    make \
  && rm -rf /var/lib/apt/lists/*

ARG GOLANG_VERSION
ARG ARCH
ARG GOLANG_BIN_SHA256
ENV GOLANG_BIN_URL https://storage.googleapis.com/golang/go$GOLANG_VERSION.linux-$ARCH.tar.gz

RUN curl -fsSL "$GOLANG_BIN_URL" -o golang.tar.gz \
  && echo "$GOLANG_BIN_SHA256  golang.tar.gz" | sha256sum -c - \
  && tar -C /usr/local -xzf golang.tar.gz \
  && rm golang.tar.gz

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH

COPY go-wrapper /usr/local/bin/
